#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
COMPILER=${APC_COMPILER:-"$REPO_ROOT/build/bin/utxo_interpreter"}
export APC_STDLIB_PATH=${APC_STDLIB_PATH:-"$REPO_ROOT/stdlib"}

if [[ ! -x "$COMPILER" ]]; then
    echo "Compiler not found or not executable: $COMPILER" >&2
    exit 1
fi

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

write_case() {
    local name=$1
    shift
    printf '%s\n' "$@" >"$TMP_DIR/$name"
}

run_compile() {
    local file=$1
    (
        cd "$TMP_DIR"
        "$COMPILER" compile "$file" >"$file.out" 2>"$file.err"
    )
}

expect_success() {
    local file=$1
    local stem=${file%.ct}

    if ! run_compile "$file"; then
        echo "Expected success for $file" >&2
        sed -n '1,120p' "$TMP_DIR/$file.err" >&2 || true
        sed -n '1,120p' "$TMP_DIR/$file.out" >&2 || true
        exit 1
    fi

    if [[ ! -s "$TMP_DIR/$stem.json" ]]; then
        echo "Expected JSON output for $file" >&2
        exit 1
    fi
}

expect_failure() {
    local file=$1
    local pattern=$2
    local stem=${file%.ct}

    set +e
    run_compile "$file"
    local rc=$?
    set -e

    if [[ $rc -eq 0 ]]; then
        echo "Expected failure for $file" >&2
        exit 1
    fi

    if [[ -e "$TMP_DIR/$stem.json" ]]; then
        echo "Unexpected JSON output for failing case $file" >&2
        exit 1
    fi

    if ! grep -q -- "$pattern" "$TMP_DIR/$file.err" "$TMP_DIR/$file.out"; then
        echo "Expected diagnostic '$pattern' for $file" >&2
        sed -n '1,120p' "$TMP_DIR/$file.err" >&2 || true
        sed -n '1,120p' "$TMP_DIR/$file.out" >&2 || true
        exit 1
    fi
}

write_case bang.ct \
    "Contract Bang:" \
    "    def main():" \
    "        Return !1"

write_case notequal.ct \
    "Contract NotEqual:" \
    "    def main():" \
    "        Return 1 != 0"

write_case two_contracts.ct \
    "Contract First:" \
    "    def main():" \
    "        Return 1" \
    "" \
    "Contract Second:" \
    "    def main():" \
    "        Return 0"

write_case trailing_garbage.ct \
    "Contract First:" \
    "    def main():" \
    "        Return 1" \
    "" \
    "THIS IS GARBAGE"

write_case return_bool_ok.ct \
    "Contract ReturnBoolOk:" \
    "    def main() -> bool:" \
    "        Return 1"

write_case return_bool_bad.ct \
    "Contract ReturnBoolBad:" \
    "    def main() -> bool:" \
    "        Return 123"

write_case bool_two.ct \
    "Contract BoolTwo:" \
    "    def main():" \
    "        flag: bool = 2" \
    "        Return flag"

write_case hex_string.ct \
    "Contract HexString:" \
    "    def main():" \
    "        h: hex = \"not hex\"" \
    "        Return h"

write_case string_num.ct \
    "Contract StringNum:" \
    "    def main():" \
    "        s: string = 1" \
    "        Return s"

write_case self_return.ct \
    "Contract SelfReturn:" \
    "    def main():" \
    "        Return self.value"

write_case no_return.ct \
    "Contract NoReturn:" \
    "    def main():" \
    "        x: int = 1"

write_case huge_num.ct \
    "Contract HugeNum:" \
    "    def main():" \
    "        Return 999999999999999999999999999999999999999999999999999999"

write_case param_array_loop_index.ct \
    "Contract ParamArrayLoopIndex:" \
    "    def main(values: int[3]):" \
    "        acc: int = 0" \
    "        for i in Range(2, -1, -1):" \
    "            acc = acc + values[i]" \
    "        Return acc"

expect_failure bang.ct "unexpected character '!'"
expect_success notequal.ct
expect_failure two_contracts.ct "unexpected token after contract definition"
expect_failure trailing_garbage.ct "unexpected token after contract definition"
expect_success return_bool_ok.ct
expect_failure return_bool_bad.ct "return type mismatch"
expect_failure bool_two.ct "type mismatch in variable declaration"
expect_failure hex_string.ct "type mismatch in variable declaration"
expect_failure string_num.ct "type mismatch in variable declaration"
expect_success self_return.ct
expect_failure no_return.ct "generated bytecode is empty"
expect_failure huge_num.ct "integer literal out of range"
expect_success param_array_loop_index.ct

python3 - "$TMP_DIR/self_return.json" <<'PY'
import json
import sys

with open(sys.argv[1], "r", encoding="utf-8") as f:
    data = json.load(f)

asm = data["lock"]["asm"].split()
assert asm and asm[0] == "<self.value>", data["lock"]["asm"]
assert "<self.value>" in data["lock"]["hex"], data["lock"]["hex"]
PY

echo "Compiler regression checks passed."
