#ifndef AST_TO_BYTECODE_PASS_H
#define AST_TO_BYTECODE_PASS_H

#include <algorithm>
#include <cctype>
#include <limits>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <typeinfo>
#include <unordered_map>
#include <utility>
#include <vector>

#include "compiler/ast_to_bytecode_converter.h"
#include "compiler/library_merger.h"
#include "config/config_manager.h"
#include "error/error_manager.h"
#include "include/pass_type.h"
#include "log/logger.h"
#include "pass/pass.h"
#include "pass/pass_context.h"
#include "pass/pass_context_keys.h"
#include "pass/pass_macros.h"
#include "util/type_utils.h"

#ifdef ENABLE_DEBUGGER
#include "debugger/info/debug_info_generator.h"
#include "debugger/info/debug_info_save.h"
#endif

class ASTToBytecodePass : public Pass
{
    DECLARE_PASS(ASTToBytecodePass)

public:
    void execute(PassContext& data) override
    {
        LOG_DEBUG("ASTToBytecodePass::execute - Start execution");

        if (!data.contains<ContractNode>(apc_pipeline::key::kAst)) {
            LOG_ERROR("ASTToBytecodePass::execute - AST data not found");
            INTERNAL_ERROR(
                "AST data not found",
                SourceLocation("", 0, 0),
                "Ensure ParserPass completed successfully before bytecode "
                "generation"
            );
            return;
        }

        auto astPtr = data.get<ContractNode>(apc_pipeline::key::kAst);
        if (!astPtr) {
            LOG_ERROR("ASTToBytecodePass::execute - AST data is empty");
            INTERNAL_ERROR(
                "AST data is empty",
                SourceLocation("", 0, 0),
                "Ensure ParserPass produced a valid contract AST"
            );
            return;
        }

        // 合并 import 的 Library 成员到 ContractNode, 由后续 visitor 做去重检查.
        const size_t merged = LibraryMerger::mergeIntoContract(*astPtr);
        if (merged > 0) {
            LOG_DEBUG(
                "ASTToBytecodePass::execute - Merged " +
                std::to_string(merged) + " library member(s) into contract '" +
                astPtr->name + "'"
            );
        }

        LOG_DEBUG(
            "ASTToBytecodePass::execute - Starting AST to bytecode conversion"
        );

        bool allowSubscopeAltstack = false;
        if (data.contains<bool>(apc_pipeline::key::kAllowSubscopeAltstack)) {
            auto allowPtr =
                data.get<bool>(apc_pipeline::key::kAllowSubscopeAltstack);
            if (allowPtr) {
                allowSubscopeAltstack = *allowPtr;
                LOG_DEBUG(
                    "ASTToBytecodePass::execute - Allow subscope altstack: " +
                    std::string(allowSubscopeAltstack ? "true" : "false")
                );
            }
        }

        std::string sourceFile = "";
        if (data.contains<std::string>(apc_pipeline::key::kSourceFilePath)) {
            auto sourceFilePtr =
                data.get<std::string>(apc_pipeline::key::kSourceFilePath);
            if (sourceFilePtr) {
                sourceFile = *sourceFilePtr;
            }
        }

        bool enableDebug = false;
        if (data.contains<bool>(apc_pipeline::key::kEnableDebug)) {
            auto enableDebugPtr =
                data.get<bool>(apc_pipeline::key::kEnableDebug);
            if (enableDebugPtr) {
                enableDebug = *enableDebugPtr;
            }
        }
#ifndef ENABLE_DEBUGGER
        (void)enableDebug;
#endif

        try {
            ASTToBytecodeConverter converter(sourceFile);
            apc_pipeline::BytecodeOutput
                bytecodeInstructions =
                    converter.convert(*astPtr, allowSubscopeAltstack);

            if (bytecodeInstructions.first.empty()) {
                LOG_WARNING("Generated bytecode is empty");
                SEMANTIC_ERROR(
                    "generated bytecode is empty",
                    SourceLocation("", 0, 0),
                    "Add at least one public function path that emits locking "
                    "script bytecode"
                );
                return;
            }

            auto abiJson = converter.getAbiJson();
            // unlock: 函数名 -> 占位符模板, 按 key 排序保证输出稳定
            nlohmann::ordered_json unlockJson =
                nlohmann::ordered_json::object();
            {
                std::map<std::string, std::string> sortedUnlock(
                    bytecodeInstructions.second.begin(),
                    bytecodeInstructions.second.end()
                );
                for (const auto& kv : sortedUnlock) {
                    unlockJson[kv.first] = kv.second;
                }
            }
            auto constructorParamsJson = converter.getConstructorParamsJson();
            auto structJson = converter.getStructJson();
            auto allFunctionsJson = converter.getAllFunctionsJson();
            auto selfPlaceholderLengths =
                converter.getSelfPlaceholderLengths();
            auto bytecodeArtifact = converter.getBytecodeArtifact();

            if (constructorParamsJson.is_array()) {
                for (const auto& parameter : constructorParamsJson) {
                    if (!parameter.is_object() ||
                        !parameter.contains("name") ||
                        !parameter["name"].is_string() ||
                        !parameter.contains("type") ||
                        !parameter["type"].is_string()) {
                        continue;
                    }
                    tbc::ConstructorFieldSchema field;
                    field.name = parameter["name"].get<std::string>();
                    field.type = parameter["type"].get<std::string>();
                    field.fixedPayloadSize =
                        fixedPayloadSizeFromType(field.type);
                    if (!field.fixedPayloadSize.has_value()) {
                        const auto fixedLength =
                            selfPlaceholderLengths.find(
                                "self." + field.name
                            );
                        if (fixedLength != selfPlaceholderLengths.end()) {
                            field.fixedPayloadSize = fixedLength->second;
                        }
                    }
                    bytecodeArtifact.constructorSchema.fields.push_back(
                        std::move(field)
                    );
                }
            }

            std::string artifactFormat = "legacy_v1";
            if (auto requested = data.tryGet<std::string>(
                    apc_pipeline::key::kArtifactFormat
                )) {
                artifactFormat = *requested;
            } else if (auto configured = ConfigManager::getInstance()
                                             .getConfigValue<std::string>(
                                                 "output.bytecode_format"
                                             )) {
                artifactFormat = *configured;
            }
            std::transform(
                artifactFormat.begin(), artifactFormat.end(),
                artifactFormat.begin(), [](unsigned char ch) {
                    return static_cast<char>(std::tolower(ch));
                }
            );
            if (artifactFormat == "canonical_v2" ||
                artifactFormat == "canonical") {
                bytecodeArtifact.format = tbc::ArtifactFormat::CanonicalV2;
            } else if (artifactFormat != "legacy_v1" &&
                       artifactFormat != "legacy") {
                SEMANTIC_ERROR(
                    "unknown bytecode artifact format '" + artifactFormat +
                        "'",
                    SourceLocation("", 0, 0),
                    "Use legacy_v1 or canonical_v2"
                );
                throw std::runtime_error(
                    "unknown bytecode artifact format"
                );
            }

            data.set(
                apc_pipeline::key::kBytecode,
                std::make_shared<apc_pipeline::BytecodeOutput>(
                    bytecodeInstructions
                )
            );
            data.set(
                apc_pipeline::key::kBytecodeArtifact,
                std::make_shared<tbc::BytecodeArtifact>(
                    std::move(bytecodeArtifact)
                )
            );
            data.set(
                apc_pipeline::key::kAbi,
                std::make_shared<nlohmann::ordered_json>(abiJson)
            );
            data.set(
                apc_pipeline::key::kUnlock,
                std::make_shared<nlohmann::ordered_json>(unlockJson)
            );
            data.set(
                apc_pipeline::key::kConstructorParams,
                std::make_shared<nlohmann::ordered_json>(constructorParamsJson)
            );
            data.set(
                apc_pipeline::key::kStructs,
                std::make_shared<nlohmann::ordered_json>(structJson)
            );
            data.set(
                apc_pipeline::key::kAllFunctions,
                std::make_shared<nlohmann::ordered_json>(allFunctionsJson)
            );
            data.set(
                apc_pipeline::key::kSelfPlaceholderLengths,
                std::make_shared<std::unordered_map<std::string, size_t>>(
                    std::move(selfPlaceholderLengths)
                )
            );
            data.set(
                apc_pipeline::key::kLifetimeCleanupApplied,
                std::make_shared<bool>(
                    converter.lifetimeOptimizationApplied()
                )
            );
            data.set(
                apc_pipeline::key::kLifetimeCleanupCount,
                std::make_shared<size_t>(
                    converter.appliedLifetimeCleanupCount()
                )
            );

            LOG_DEBUG(
                "ASTToBytecodePass::execute - Stored ABI data in PassContext"
            );

#ifdef ENABLE_DEBUGGER
            if (enableDebug) {
                auto debugInfoGen = converter.getDebugInfoGenerator();
                if (debugInfoGen) {
                    auto debugInfo = debugInfoGen->getDebugInfo();
                    data.set(apc_pipeline::key::kDebugInfo, debugInfo);

                    apc_debug::DebugInfoSaveOptions saveOptions;
                    saveOptions.useDefaultOutputFile = true;
                    saveOptions.respectSuppressFlag = true;
                    saveOptions.logSuccessStats = true;
                    apc_debug::saveDebugInfoIfRequested(
                        data, debugInfo, saveOptions
                    );
                } else {
                    LOG_WARNING("调试信息生成器未初始化");
                }
            }
#endif

        } catch (const std::exception& e) {
            LOG_ERROR(
                "ASTToBytecodePass::execute - Exception occurred during "
                "bytecode generation: ",
                e.what()
            );
            if (!ErrorManager::getInstance().hasErrors()) {
                INTERNAL_ERROR(
                    std::string("bytecode generation failed: ") + e.what(),
                    SourceLocation("", 0, 0),
                    "This is an internal compiler error. Please report this "
                    "issue"
                );
            }
        } catch (...) {
            LOG_ERROR("ASTToBytecodePass::execute - Unknown exception occurred "
                      "during bytecode generation");
            if (!ErrorManager::getInstance().hasErrors()) {
                INTERNAL_ERROR(
                    "unknown bytecode generation failure",
                    SourceLocation("", 0, 0),
                    "This is an internal compiler error. Please report this "
                    "issue"
                );
            }
        }

        LOG_DEBUG("ASTToBytecodePass::execute - Execution completed");
    }

    std::vector<std::string> getDependencies() const override
    {
        return {DependTypeToString(DependType::ParserPass)};
    }

private:
    static std::optional<size_t> fixedPayloadSizeFromType(
        const std::string& type
    )
    {
        auto parseHexLength = [](const std::string& value)
            -> std::optional<size_t> {
            if (value.rfind("hex", 0) != 0 || value.size() <= 3) {
                return std::nullopt;
            }
            const std::string digits = value.substr(3);
            if (!std::all_of(
                    digits.begin(), digits.end(), [](unsigned char ch) {
                        return std::isdigit(ch) != 0;
                    }
                )) {
                return std::nullopt;
            }
            try {
                const size_t parsed = std::stoull(digits);
                return parsed == 0 ? std::nullopt
                                   : std::optional<size_t>(parsed);
            } catch (...) {
                return std::nullopt;
            }
        };

        if (const auto arrayType = apc::util::parseFixedArrayType(type)) {
            const auto elementLength =
                arrayType->elementType == "uint64"
                    ? std::optional<size_t>(8)
                    : parseHexLength(arrayType->elementType);
            if (!elementLength.has_value() || arrayType->size == 0 ||
                arrayType->size >
                    std::numeric_limits<size_t>::max() /
                        *elementLength) {
                return std::nullopt;
            }
            return arrayType->size * *elementLength;
        }
        if (const auto hexLength = parseHexLength(type)) {
            return hexLength;
        }
        if (type == "uint64") {
            return 8;
        }
        if (type == "bool" || type == "boolean") {
            return 1;
        }
        if (type == "ripemd160" || type == "pubkeyhash" ||
            type == "sha1" || type == "address") {
            return 20;
        }
        if (type == "sha256" || type == "privkey") {
            return 32;
        }
        return std::nullopt;
    }
};

#endif // AST_TO_BYTECODE_PASS_H
